# Lab_
this file has been made to check some data features

## Load_data

In [1]:
from pathlib import Path
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
data_path = Path("..") / '01_Data' / 'heart_cleaned.csv'
data = pd.read_csv(data_path)
data.head(7)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,age_group
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,Old
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,Young
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,Middle
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,Middle
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,Middle
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1,Middle
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1,Middle

In [3]:
onehot_enc = OneHotEncoder(sparse_output=False)

encoded = onehot_enc.fit_transform(data[['age_group']])

encoded_df = pd.DataFrame(
    encoded,
    columns=onehot_enc.get_feature_names_out(['age_group']),
    index=data.index
)

data = pd.concat(
    [data.drop(columns=['age_group']), encoded_df],
    axis=1
)
data.head(7)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,age_group_Middle,age_group_Old,age_group_Young
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,0.0,1.0,0.0
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,0.0,0.0,1.0
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,1.0,0.0,0.0
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,1.0,0.0,0.0
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,1.0,0.0,0.0
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1,1.0,0.0,0.0
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1,1.0,0.0,0.0

In [ ]:
std_scaler = StandardScaler()
features = ['age','trestbps','chol','thalach','oldpeak']
data[features] = std_scaler.fit_transform(data[features])

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,age_group_Middle,age_group_Old,age_group_Young
0,0.952197,1,3,0.763956,-0.256334,1,0,0.015443,0,1.087338,0,0,1,1,0.0,1.0,0.0
1,-1.915313,1,2,-0.092738,0.072199,0,1,1.633471,0,2.122573,0,0,2,1,0.0,0.0,1.0
2,-1.474158,0,1,-0.092738,-0.816773,0,0,0.977514,0,0.310912,2,0,2,1,1.0,0.0,0.0
3,0.180175,1,1,-0.663867,-0.198357,0,1,1.239897,0,-0.206705,2,0,2,1,1.0,0.0,0.0
4,0.290464,0,0,-0.663867,2.082050,0,1,0.583939,1,-0.379244,2,0,2,1,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.290464,0,0,0.478391,-0.101730,0,1,-1.165281,1,-0.724323,1,0,3,0,1.0,0.0,0.0
299,-1.033002,1,3,-1.234996,0.342756,0,1,-0.771706,0,0.138373,1,0,3,0,1.0,0.0,0.0
300,1.503641,1,0,0.706843,-1.029353,1,1,-0.378132,0,2.036303,1,2,3,0,0.0,1.0,0.0
301,0.290464,1,0,-0.092738,-2.227533,0,1,-1.515125,1,0.138373,1,1,3,0,1.0,0.0,0.0
302,0.290464,0,1,-0.092738,-0.198357,0,0,1.064975,0,-0.896862,1,1,2,0,1.0,0.0,0.0