# Lab_
this file has been made to check some data features

## Load_data

In [4]:
from pathlib import Path
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [5]:
data_path = Path("..") / '01_Data' / 'heart_cleaned.csv'
data = pd.read_csv(data_path)
data.head(7)

   age  sex  cp  trestbps  chol  ...  slope  ca  thal  target  age_group
0   63    1   3       145   233  ...      0   0     1       1        Old
1   37    1   2       130   250  ...      0   0     2       1      Young
2   41    0   1       130   204  ...      2   0     2       1     Middle
3   56    1   1       120   236  ...      2   0     2       1     Middle
4   57    0   0       120   354  ...      2   0     2       1     Middle
5   57    1   0       140   192  ...      1   0     1       1     Middle
6   56    0   1       140   294  ...      1   0     2       1     Middle

[7 rows x 15 columns]

In [6]:
onehot_enc = OneHotEncoder(sparse_output=False)

encoded = onehot_enc.fit_transform(data[['age_group']])

encoded_df = pd.DataFrame(
    encoded,
    columns=onehot_enc.get_feature_names_out(['age_group']),
    index=data.index
)

data = pd.concat(
    [data.drop(columns=['age_group']), encoded_df],
    axis=1
)
data.head(7)

   age  sex  cp  ...  age_group_Middle  age_group_Old  age_group_Young
0   63    1   3  ...               0.0            1.0              0.0
1   37    1   2  ...               0.0            0.0              1.0
2   41    0   1  ...               1.0            0.0              0.0
3   56    1   1  ...               1.0            0.0              0.0
4   57    0   0  ...               1.0            0.0              0.0
5   57    1   0  ...               1.0            0.0              0.0
6   56    0   1  ...               1.0            0.0              0.0

[7 rows x 17 columns]

In [7]:
std_scaler = StandardScaler()
features = ['age','trestbps','chol','thalach','oldpeak']
data[features] = std_scaler.fit_transform(data[features])

## train_test_split

In [8]:
X = data.drop(columns=['target'],axis=1)
y = data['target']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(f'X_train_shape: {X_train.shape}')
print(f'X_test_shape: {X_test.shape}')
print(f'y_train_shape: {y_train.shape}')
print(f'y_test_shape : {y_test.shape}')

X_train_shape: (242, 16)
X_test_shape: (61, 16)
y_train_shape: (242,)
y_test_shape : (61,)